FROM ubuntu:22.04

ENV LLVM_DIR /usr/lib/llvm-13/
ENV TUTOR_DIR /llvm-tutor


RUN useradd -m vscode -s /bin/bash
WORKDIR /home/vscode
ENV HOME /home/vscode

# Based on LLVM 13 beacuse SVF support llvm 13.

RUN sed -i "s/archive.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g" /etc/apt/sources.list \
    && sed -i "s/security.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g" /etc/apt/sources.list \
    && apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends sudo openssh-client build-essential cmake ninja-build git wget lsb-release curl socat software-properties-common python3-minimal python3-pip python3-setuptools gpg-agent zlib1g-dev gdb gdbserver \
    && wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - \
    && apt-add-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-13 main" \
    && apt-get update \
    && apt-get install -y llvm-13 llvm-13-dev llvm-13-tools clang-13 \
    && pip3 install lit \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && echo 'vscode:123456' | chpasswd \
    && echo "vscode ALL=(ALL) NOPASSWD:ALL" | tee -a /etc/sudoers

USER vscode

# TODO
# curl https://wasmtime.dev/install.sh -sSf | bash
# wasi-sdk install to /opt, add to path

