[book]
authors = ["am009"]
language = "en"
multilingual = false
src = "src"
title = "NotDec: Decompiler From Scratch"

[output.html]
git-repository-url = "https://github.com/NotDec/notdec"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/NotDec/NotDec/edit/main/docs/{path}"
